### ISSUE TITLE
Option to not panic when `error()` is called in Lua script

### ISSUE THREAD

**Issue by poga** [poga/actix-lua#17]
Before `0.4.0` and `0.3.4`, if `error()` is called inside the Lua script, it will be consumed silently. Now it will panic with proper stack trace.

It's easiler to debug now. But, sometimes panicking is too destructive. One use-case is a live-reloading environment. We might want to just show the error trace and continue the execution, allows user to have a chance to fix their script without restarting the whole program.

This is mostly about the last part of the `invoke` function in `actor.rs`. Maybe we should return a `Err` instead of just `panic!`.

**Comment by poga** [comment]
https://github.com/poga/actix-lua/commit/67e15ca90785820e1c06fbc8b273fcf3eb49372b added an example about hot-reloading with `pcall`. I think this is good enough.

**Comment by Arnaz87** [comment]
This solution doesn't allow one access to the error information, because the debug library is disabled for safety reasons

**Comment by poga** [comment]
and yea, we still should return an `Err` instead of panicking.

**Comment by Arnaz87** [comment]
I need to log the stack trace of the error, sometimes only the loc isn't enough to track down an error, but the tace is only accesible in debug.traceback, which is disallowed.

**Comment by poga** [comment]
From what I understand, `rlua::Error.backtrace()` is only implemented for `ExternalError`. (https://github.com/kyren/rlua/blob/master/src/error.rs#L194). An `ExternalError` is used when you want to return error **from rust callbacks to lua**. Hence it's not really useful for debugging Lua errors.

**Comment by poga** [comment]
`rlua` does provide [an unsafe method](https://docs.rs/rlua/0.15.3/rlua/struct.Lua.html#method.new_with_debug) for loading debug library into lua state. We can have an unsafe `new_with_debug` method for `LuaActorBuilder` to build a `LuaActor` with the debug library.

I've opened https://github.com/poga/actix-lua/issues/18. Feel free to tackle it.
