### ISSUE TITLE
Actix web demo

### ISSUE THREAD

**Issue by mitchtbaum** [poga/actix-lua#2]
Would you please make a Lua webserver demo?

**Comment by poga** [comment]
I've added an example about using `actix-lua` with `actix-web` at https://github.com/poga/actix-lua/tree/master/examples/http-server

Feel free to ask if you have any question.

**Comment by poga** [comment]
Sure. There are two way to achieve it off top of my head:

First, you can write a catch all route in `actix-web` and do routing and handling all inside the lua actor.

Or you can parse routing config written in lua and generate an `actix-web` application based on the config.
