### ISSUE TITLE
Typed functions panic on wrong argument types

### ISSUE THREAD

**Issue by Arnaz87** [poga/actix-lua#22]
When lua calls rust defined functions with wrong argument types it panics the thread, it doesn't propagate the error for lua or rust to handle it, it straight up panics.

It may happen with any error returned by rust code called from lua handler code, but I don't know, I just saw it happen with wrong typed arguments.

**Comment by mitchtbaum** [comment]
(not meant to speak to this issue really, but static analysis of lua code is possible and potentially useful for other environmental programmability improvements)

**Comment by Arnaz87** [comment]
Relevant lines in the stack backtrace
~~~
  17: <actix_lua::message::LuaMessage as rlua::value::FromLua<'lua>>::from_lua
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/actix-lua-0.5.1/src/message.rs:120
  18: actix_lua::actor::invoke::{{closure}}
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/actix-lua-0.5.1/src/actor.rs:224
  19: rlua::lua::Lua::scope
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/rlua-0.15.3/src/lua.rs:369
  20: actix_lua::actor::invoke
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/actix-lua-0.5.1/src/actor.rs:145
  21: <actix_lua::actor::LuaActor as actix::handler::Handler<actix_lua::message::LuaMessage>>::handle
             at .../.cargo/registry/src/github.com-1ecc6299db9ec823/actix-lua-0.5.1/src/actor.rs:286
~~~

**Comment by poga** [comment]
can you provide a minimum reproducible example?

**Comment by Arnaz87** [comment]
https://gist.github.com/Arnaz87/550bee2ec9f59aae05952cceb8192878

It doesn't panic...

**Comment by Arnaz87** [comment]
In the original code, this is the error message, I forgot to say it

~~~
thread 'arbiter:5037cb99-0989-4fb1-b855-945ba10943dc:actor' panicked at 'Lua error: FromLuaConversionError { from: "nil", to: "String", message: Some("expected string or number") }', .../.cargo/registry/src/github.com-1ecc6299db9ec823/actix-lua-0.5.1/src/message.rs:123:17 
~~~

**Comment by mitchtbaum** [comment]
@Arnaz87 you left out code comments..  which function expects a typed input?  where does it get called with a different type?

**Comment by Arnaz87** [comment]
[This](https://github.com/foundpatterns/lighttouch-html-interface/commit/90ca60e617b8915a55f9815e8cd90a5b62d6ba34) is an instance of it happening in the code i'm working on, uuid.check is defined [here](https://github.com/foundpatterns/torchbear/blob/34c2567d019d231e324e3c7c4dafb8bea15d5c14/src/bindings/uuid.rs#L11-L13), it expects a string and if I pass a nil the thread panics.

**Comment by Arnaz87** [comment]
I modified the gist to explain what is happening and what should happen, it's in `main.lua`

**Comment by mitchtbaum** [comment]
A bit more context:

In [Lighttouch](/foundpatterns/lighttouch),  built on [Torchbear](/foundpatterns/torchbear), [`uuid.check`](https://github.com/foundpatterns/torchbear/blob/master/src/bindings/uuid.rs#L11-L13) broke with a nil input in our [witness action](https://github.com/foundpatterns/lighttouch-html-interface/blob/master/actions/witness.lua).  In https://github.com/foundpatterns/lighttouch-html-interface/commit/90ca60e617b8915a55f9815e8cd90a5b62d6ba34, Arnaud added a line to prevent passing nil as a parameter, because `uuid.check` expects a string, and if it's passed something else it panics.

**Comment by poga** [comment]
It's kinda hard for me to understand what happened since I can't reproduce the panic with your example. :p

**Comment by mitchtbaum** [comment]
Arnaud struggled the whole day to distill it to a working test.  I told him, then we need to at least give you something you can reproduce; that way we can either come back to it later with more info, or so that with it you can catch up to speed with the code built on top of yours and help.  That's the best we have so far.

Could I interest you in a crash course in [Lighttouch](/foundpatterns/lighttouch)?  I promise you'll enjoy it, or your money back! ;)

**Comment by poga** [comment]
Since I can't reproduce the panic with neither pure rlua nor actix-lua. Here's my suggestion to check:

1. You forget to wrap a function call with `pcall`
2. You're using `pcall` as `pcall(function(args))`. It should be `pcall(function, args)`.

**Comment by Arnaz87** [comment]
Here is a minimum reproducible example:

https://github.com/Arnaz87/Actix-lua-test

It copies the structure of the project with the bug. The error trigger is in `main.lua`.

**Comment by poga** [comment]
https://github.com/Arnaz87/Actix-lua-test/blob/master/main.lua#L11 You need to wrap the call to `myfn` with `pcall`.

Change it to `local ok, ret = print(pcall(myfn,nil))` and the panic is gone.

**Comment by mitchtbaum** [comment]
@poga here's the error running  https://github.com/Arnaz87/Actix-lua-test
Arnaud didn't tell me anymore than that he reproduced the bug

**Comment by Arnaz87** [comment]
No, it's already wrapped in an xpcall, change that line for `error("My error")` and see the error handler is triggered. The xpcall is [Here](https://github.com/Arnaz87/Actix-lua-test/blob/cb994243179fa0ae8dc31dd240b9760ad3ef4ec7/handler.lua#L5-L15).

**Comment by Arnaz87** [comment]
Yes, you are right, this was the problem. I made a rust function that converts an error to a string. Thanks for helping me solve it.

It would be nice if rlua did that itself though.

**Comment by Arnaz87** [comment]
Actually `tostring(msg)` does work on lua errors, that's the better solution.

**Comment by poga** [comment]
🎉
