### ISSUE TITLE
actix-lua-web framework

### ISSUE THREAD

**Issue by mitchtbaum** [poga/actix-lua#5]
This [actix-lua-web framework gist](https://gist.github.com/mitchtbaum/0b757775e3f3205e2fe9c87e8befb667) has a more complex example that relies on [serde-yaml](https://github.com/dtolnay/serde-yaml) and [tera](https://github.com/Keats/tera).  Does it make sense?

**Comment by poga** [comment]
is the gist complete? I don't see anything related to serde-yaml or actix-lua.

**Comment by mitchtbaum** [comment]
yes.  there are 2 content files, 2 template files, and 1 script file. here's a walkthrough of what I mean to show:

- the content files have file names of their UUID and unix atime and mtime
- they have a yaml header for metadata and a plain text body separated by a blank line
- the template files are jinja syntax meant to be rendered using tera
- they are json http responses, 1 for individual documents and 1 for listing a group of documents
- the script file is Lua pseudo code, with 2 chunks, meant to be called on every request
- the first chunk responds to requests for individual files, eg. `/post/50ee670c-1e2a-4ed7-8558-1dd6a87dbe8e` would read the content file with that uuid in the 'content' directory and render it using the `document.json` template
- the second chunk responds to requests for a list of content files, eg every file with `type: post`, and renders it using the `document-list.json` template

**Comment by poga** [comment]
Thanks for the elaboration. Yes. It's definitely possible to create something like this.

It can be a good example about how to write a conventional web framework on top of `actix-lua`. If anyone want to try, I'm willing to help.

**Comment by poga** [comment]
I've added an example about using pure-lua to build a basic framework: https://github.com/poga/actix-lua/tree/master/examples/lua-web. You don't need `serde-yaml` or other rust libraries to achieve it.

**Comment by poga** [comment]
closing
