### ISSUE TITLE
Please add a Gitter chatroom

### ISSUE THREAD

**Issue by mitchtbaum** [poga/actix-lua#6]
Thank you.

**Comment by poga** [comment]
IMO github issue is enough for now. We don't have a lot of traffic right now. Putting them in one place makes it easier to follow.

I understand that creating good issue is hard. But I believe a written, complete issue is better than fragmented chat conversation. [I've setup issue templates to lower the barrier of creating issues](https://github.com/poga/actix-lua/commit/ccfd09e4f473c03c8bdfd985e5e47dd8fcbf0257). 

I will look for other solution if it becomes unmanageable.
